version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend_flask:latest
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development